[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build:web"

[deploy]
startCommand = "npx serve web-build --listen $PORT --single"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"